### ISSUE TITLE
Overrides clear command in terminal

### ISSUE THREAD

**Issue by TimSchulzRC** [ServBay/ServBay#2]
Why the hell does it override the clear command???
It took me way too long to figure out why I cannot clear my terminal anymore...

**Comment by goktugcy** [comment]
Solution : nano ~/.bashrc or ~/.zshrc add this command  ;

 export TERMINFO=/usr/share/terminfo 

The interface and functionality are nice, but there are some ridiculous problems.

**Comment by naizhao** [comment]
Sorry for the inconvenience, you can delete the /Applications/ServBay/bin/clear command. The subsequent Runtime will handle this problem.
