### ISSUE TITLE
Your bot is spamming unrelated GitHub issues

### ISSUE THREAD

**Issue by iameli-streams** [ServBay/ServBay#4]
Please stop. Some examples:

https://github.com/cirruslabs/gitlab-tart-executor/issues/90#issuecomment-2449037095
https://github.com/d12frosted/homebrew-emacs-plus/issues/742#issuecomment-2449099193
https://github.com/paulbalandan/liaison-revision/issues/2#issuecomment-2434194058
https://github.com/nus-apr/auto-code-rover/issues/72#issuecomment-2440735852

**Comment by naizhao** [comment]
Sorry for the inconvenience. I'll ask my colleagues to check what's going on.
